export const PlayerActionTypes = {
  SET_PLAYER_COLOR: 'SET_PLAYER_COLOR',
  SET_THROWN_NUMBER: 'SET_THROWN_NUMBER',
  SET_STONES: 'SET_STONES',
  SET_FIELD_ARRAY: 'SET_FIELD_ARRAY',
  SET_DICE_URL: 'SET_DICE_URL',
  SET_GAME_START: 'SET_GAME_START',
  SET_PLAYERS_NAME: 'SET_PLAYERS_NAME'
}